on:
  pull_request:
    types: closed

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          default_bump: minor 
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn install
          yarn build
      - uses: marvinpinto/action-automatic-releases@latest
        with: # See https://github.com/marvinpinto/action-automatic-releases/tree/v1.1.0#supported-parameters
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.tag_version.outputs.new_tag }}"
          prerelease: false
          title: "LFUI-icons ${{ steps.tag_version.outputs.new_tag }}"    
          
          
      
