# Summary:
# Automatically tag and release when changes land on any branch.
# Tag and release changes on the master branch, as releases. (one release per commit)
# Tag and pre-release changes on the other branches, as pre-releases with a "x" as "patch" indicator.
#  (one release per branch, the release is updated at every push)
#
# Dependencies overview:
# - See https://github.com/PaulHatch/semantic-version https://github.com/PaulHatch/semantic-version/tree/v3.2
# - See https://github.com/marvinpinto/action-automatic-releases https://github.com/marvinpinto/action-automatic-releases/tree/v1.1.0
# - See https://github.com/rlespinasse/github-slug-action https://github.com/rlespinasse/github-slug-action/tree/3.x

name: 'Auto release'
on:
  pull_request:
    types: closed

jobs:
  tag-and-release:
    runs-on: ubuntu-18.04
    timeout-minutes: 5 # Limit current job timeout https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
    steps:
      - name: Expose GitHub slug/short variables # See https://github.com/rlespinasse/github-slug-action#exposed-github-environment-variables
        uses: rlespinasse/github-slug-action@v3.x # See https://github.com/rlespinasse/github-slug-action
      - uses: actions/checkout@v2 # See https://github.com/actions/checkout
        with:
          fetch-depth: 0 # See https://github.com/PaulHatch/semantic-version#important-note-regarding-the-checkout-action
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn install
          yarn build
      - uses: paulhatch/semantic-version@v3.2 # See https://github.com/PaulHatch/semantic-version
        id: next_semantic_version # Output: https://github.com/PaulHatch/semantic-version/blob/master/index.js#L63-L69
        with: # See https://github.com/PaulHatch/semantic-version#usage
          branch: ${{ env.GITHUB_REF_SLUG }} # Use current branch
          tag_prefix: "v" # The prefix to use to identify tags
          major_pattern: "(MAJOR)" # A string which, if present in a git commit, indicates that a change represents a major (breaking) change
          minor_pattern: "(MINOR)" # Same as above except indicating a minor change
          format: "${major}.${minor}.${patch}-${{ env.GITHUB_REF_SLUG }}" # A string to determine the format of the version output
          short_tags: false # If set to false, short tags like "v1" will not be considered, only full versions tags such as "v1.0.0" will be used to determine the version.
          bump_each_commit: true # If this input is set to true, every commit will be treated as a new version, bumping the patch, minor, or major version based on the commit message.
      - run: |
          echo "Branch name: ${{ env.GITHUB_REF_SLUG }}"
          echo ${{ join(steps.next_semantic_version.outputs.*, ' - ') }}
          echo "Next version: ${{ steps.next_semantic_version.outputs.version }}"
          echo "Next version tag: ${{ steps.next_semantic_version.outputs.version_tag }}"
      # Auto-release when a commit hit "master"
      - uses: marvinpinto/action-automatic-releases@10bdce64abdb4558a2ee6983192242be40d631d8 # Pin "latest" https://github.com/marvinpinto/action-automatic-releases/commit/10bdce64abdb4558a2ee6983192242be40d631d8 necessary to avoid "The `set-env` command is disabled."
        if: startsWith(env.GITHUB_REF_SLUG, 'v2-') || env.GITHUB_REF_SLUG == 'master' || env.GITHUB_REF_SLUG == 'main' # If master, mark release as official release
        with: # See https://github.com/marvinpinto/action-automatic-releases/tree/v1.1.0#supported-parameters
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.next_semantic_version.outputs.version }}"
          prerelease: false
          title: "LFUI-icons ${{ steps.next_semantic_version.outputs.version_tag }} (from `${{ env.GITHUB_REF_SLUG }}`)"
          files: |
            CHANGELOG.md
     
