# This workflow will run tests and build icons for LFUI v2 when a pull request to branch support/2.x is closed.
# It's required that the pull request have a 'minor' or 'patch' label on it.
# The NPM package will be published with the v2-patch tag.

name: Node.js Package

on:
  pull_request:
    types: 
      - closed
    branches:
      - 'support/2.x'

jobs:
  check_labels:
    name: 'Check PR Labels'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mheap/github-action-required-labels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: 'minor, patch'
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Test
        run: npm test

      - name: Pre-build
        run: npm run prebuild

      - name: Build
        run: npm run build

  publish-npm:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@lansforsakringar'
          
      - name: Apply version bump (minor)
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: npm version minor
      - name: Apply version bump (patch)
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: npm version patch
      
      - name: Bump version
        run: npm version ${{ github.event.release.tag_name }}
        
      - run: npm publish --tag v2-patch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        
